name: insilico
channels:
- r
- cyclus
- defaults
dependencies:
- python=3.6
- r=3.3.2
- java-jdk=8.25
- rpy2=2.8.5
- r-rjava=0.9_8
- ipython
- jinja2
- matplotlib
- numpy=1.11
- pandas=0.19.2
- pytest=3
- pyyaml
- scikit-learn=0.18.1
- seaborn
- sphinx=1.5
- xlrd
- pandoc=1.19
- graphviz
